on:
  push:
    branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  octokit-graphql-test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v3

      - run: |
          cat '${{ github.event_path }}'
          
      - name: Report Breaking Changes
        uses: tmillr/breaking-change@garbage
#         if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        with:
          issueNumber: 2
          discussionNumber: 1
